"""empty message

Revision ID: 18a64c206aab
Revises: 341220c64685
Create Date: 2025-11-21 15:13:28.581246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a64c206aab'
down_revision = '341220c64685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_years', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_of_joining', sa.Date(), nullable=True))

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('emergency_contact')
        batch_op.drop_column('secondary_phone')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('date_of_joining')
        batch_op.drop_column('experience_years')

    # ### end Alembic commands ###
