"""empty message

Revision ID: 2216141cf18f
Revises: bef6d388ba89
Create Date: 2025-11-25 17:20:09.101272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2216141cf18f'
down_revision = 'bef6d388ba89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('secondary_phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_phone', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
