"""empty message

Revision ID: 9bb5577d3d60
Revises: 3658e3de7953
Create Date: 2025-11-22 01:17:19.931688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb5577d3d60'
down_revision = '3658e3de7953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_availability_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_availability_doctor_id'), ['doctor_id'], unique=False)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('diagnosis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('treatment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('prescription', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uix_doctor_date_time'), type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('time')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('availability_json')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('time', sa.TIME(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uix_doctor_date_time'), ['doctor_id', 'date', 'time'])
        batch_op.drop_column('prescription')
        batch_op.drop_column('treatment')
        batch_op.drop_column('diagnosis')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_availability_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_doctor_availability_date'))

    op.drop_table('doctor_availability')
    # ### end Alembic commands ###
