"""empty message

Revision ID: bdba8715479d
Revises: 9bb5577d3d60
Create Date: 2025-11-22 01:32:20.320297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdba8715479d'
down_revision = '9bb5577d3d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=False))
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')
        batch_op.drop_column('diagnosis')
        batch_op.drop_column('prescription')
        batch_op.drop_column('treatment')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('availability')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment_notes', sa.Text(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('treatment_notes')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.TEXT(), nullable=True))

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability', sa.TEXT(), nullable=True))

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('prescription', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('diagnosis', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.TIME(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.TIME(), nullable=False))
        batch_op.drop_column('time')

    # ### end Alembic commands ###
