"""empty message

Revision ID: bef6d388ba89
Revises: fa9c26171d17
Create Date: 2025-11-24 02:55:24.459193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef6d388ba89'
down_revision = 'fa9c26171d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('treatment_notes')
        batch_op.drop_column('diagnosis')
        batch_op.drop_column('prescription')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescription', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('diagnosis', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('treatment_notes', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
